### ISSUE TITLE
Sidebar Content Hidden Due to Missing Scrollbar

### ISSUE THREAD

**Issue by ausane** [manuarora700/sidefolio#4]
The sidebar on your repository's page at [https://sidefolio.vercel.app](url) lacks a scrollbar, causing some of the content to be hidden and inaccessible. This issue affects navigation and user experience, as important links and information are not visible.

Screenshot:

![Screenshot 2024-07-20 125023](https://github.com/user-attachments/assets/e7bda9c6-2bfa-4578-b94d-79d47a2bbb57)

**Comment by manuarora700** [comment]
Fixed in the latest commit @ausane
