### ISSUE TITLE
[Mobile Bug] "Read Resume" Button in Sidebar Does Not Close Sidebar

### ISSUE THREAD

**Issue by ausane** [manuarora700/sidefolio#5]
## `Read Resume` Button in Sidebar Does Not Close Sidebar
In the mobile viewport of your repository's page at [https://sidefolio.vercel.app](url) clicking the `Read Resume` button in the sidebar does not close the sidebar as expected. Instead, the sidebar remains open. This issue affects the user experience by obstructing the main content when the sidebar should be hidden.

### Expected Behavior:
Clicking the `Read Resume` button in the sidebar should close the sidebar.

### Actual Behavior:
The sidebar stays open when the `Read Resume` button is clicked.

### Video:
https://github.com/user-attachments/assets/124e5863-f433-4f6c-b08d-25f875c8ca56

**Comment by manuarora700** [comment]
Fixed in the latest commit @ausane
